import { Lead } from "@/types/lead";

/** Convert a Lead object to a database row (camelCase → snake_case) */
export function leadToRow(lead: Lead): Record<string, any> {
  return {
    id: lead.id,
    brand: lead.brand,
    name: lead.name,
    email: lead.email,
    phone: lead.phone,
    company: lead.company,
    company_url: lead.companyUrl,
    role: lead.role,
    source: lead.source,
    date_submitted: lead.dateSubmitted,
    message: lead.message,
    deals_planned: lead.dealsPlanned,
    stage: lead.stage,
    service_interest: lead.serviceInterest,
    deal_value: lead.dealValue,
    assigned_to: lead.assignedTo,
    meeting_date: lead.meetingDate,
    meeting_set_date: lead.meetingSetDate,
    hours_to_meeting_set: lead.hoursToMeetingSet,
    days_in_current_stage: lead.daysInCurrentStage,
    stage_entered_date: lead.stageEnteredDate,
    close_reason: lead.closeReason,
    closed_date: lead.closedDate,
    notes: lead.notes,
    last_contact_date: lead.lastContactDate,
    next_follow_up: lead.nextFollowUp,
    priority: lead.priority,
    meeting_outcome: lead.meetingOutcome,
    forecast_category: lead.forecastCategory,
    icp_fit: lead.icpFit,
    pre_screen_completed: lead.preScreenCompleted ?? false,
    won_reason: lead.wonReason,
    lost_reason: lead.lostReason,
    subscription_value: lead.subscriptionValue,
    billing_frequency: lead.billingFrequency,
    contract_start: lead.contractStart,
    contract_end: lead.contractEnd,
    target_criteria: lead.targetCriteria,
    target_revenue: lead.targetRevenue,
    geography: lead.geography,
    current_sourcing: lead.currentSourcing,
    is_duplicate: lead.isDuplicate,
    duplicate_of: lead.duplicateOf,
    hear_about_us: lead.hearAboutUs,
    acquisition_strategy: lead.acquisitionStrategy,
    buyer_type: lead.buyerType,
    fireflies_url: lead.firefliesUrl,
    fireflies_transcript: lead.firefliesTranscript,
    fireflies_summary: lead.firefliesSummary,
    fireflies_next_steps: lead.firefliesNextSteps,
    linkedin_url: lead.linkedinUrl,
    linkedin_title: lead.linkedinTitle,
    meetings: lead.meetings || [],
    submissions: lead.submissions || [],
    enrichment: lead.enrichment || null,
    deal_intelligence: lead.dealIntelligence || null,
    stage1_score: lead.stage1Score,
    stage2_score: lead.stage2Score,
    tier: lead.tier,
    tier_override: lead.tierOverride,
    enrichment_status: lead.enrichmentStatus,
    created_at: lead.createdAt,
    calendly_booked_at: lead.calendlyBookedAt,
    calendly_event_name: lead.calendlyEventName,
    calendly_event_type: lead.calendlyEventType,
    calendly_event_duration: lead.calendlyEventDuration,
    secondary_contacts: lead.secondaryContacts || [],
    google_drive_link: lead.googleDriveLink,
    forecasted_close_date: lead.forecastedCloseDate,
    next_mutual_step: lead.nextMutualStep || "",
    next_mutual_step_date: lead.nextMutualStepDate || "",
    competing_bankers: lead.competingBankers || "",
    contract_months: lead.contractMonths ?? null,
    close_confidence: lead.closeConfidence ?? null,
    deal_narrative: lead.dealNarrative || "",
    firm_aum: lead.firmAum || "",
    acq_timeline: lead.acqTimeline || "",
    active_searches: lead.activeSearches || "",
    budget_confirmed: lead.budgetConfirmed || "",
    authority_confirmed: lead.authorityConfirmed || "",
    ebitda_min: lead.ebitdaMin || "",
    ebitda_max: lead.ebitdaMax || "",
    deal_type: lead.dealType || "",
    transaction_type: lead.transactionType || "",
    competing_against: lead.competingAgainst || "",
    decision_blocker: lead.decisionBlocker || "",
    sample_sent_date: lead.sampleSentDate || "",
    sample_outcome: lead.sampleOutcome || "",
    proof_notes: lead.proofNotes || "",
    stall_reason: lead.stallReason || "",
    // v2 pipeline fields
    lost_reason_v2: lead.lostReasonV2 || "",
    nurture_sequence_status: lead.nurtureSequenceStatus ?? null,
    nurture_started_at: lead.nurtureStartedAt ?? null,
    nurture_re_engage_date: lead.nurtureReEngageDate ?? null,
    stage_gate_overrides: lead.stageGateOverrides ?? [],
    discovery_call_completed_at: lead.discoveryCallCompletedAt ?? null,
  };
}

/** Convert a database row to a Lead object (snake_case → camelCase) */
export function rowToLead(row: Record<string, any>): Lead {
  return {
    id: row.id,
    brand: row.brand,
    name: row.name,
    email: row.email,
    phone: row.phone,
    company: row.company,
    companyUrl: row.company_url || "",
    role: row.role,
    source: row.source,
    dateSubmitted: row.date_submitted || "",
    message: row.message || "",
    dealsPlanned: row.deals_planned || "",
    stage: row.stage,
    serviceInterest: row.service_interest || "TBD",
    dealValue: Number(row.deal_value) || 0,
    assignedTo: row.assigned_to || "",
    meetingDate: row.meeting_date || "",
    meetingSetDate: row.meeting_set_date || "",
    hoursToMeetingSet: row.hours_to_meeting_set != null ? Number(row.hours_to_meeting_set) : null,
    daysInCurrentStage: Number(row.days_in_current_stage) || 0,
    stageEnteredDate: row.stage_entered_date || "",
    closeReason: row.close_reason || "",
    closedDate: row.closed_date || "",
    notes: row.notes || "",
    lastContactDate: row.last_contact_date || "",
    nextFollowUp: row.next_follow_up || "",
    priority: row.priority || "Medium",
    meetingOutcome: row.meeting_outcome || "",
    forecastCategory: row.forecast_category || "",
    icpFit: row.icp_fit || "",
    preScreenCompleted: row.pre_screen_completed ?? false,
    wonReason: row.won_reason || "",
    lostReason: row.lost_reason || "",
    subscriptionValue: Number(row.subscription_value) || 0,
    billingFrequency: row.billing_frequency || "",
    contractStart: row.contract_start || "",
    contractEnd: row.contract_end || "",
    targetCriteria: row.target_criteria || "",
    targetRevenue: row.target_revenue || "",
    geography: row.geography || "",
    currentSourcing: row.current_sourcing || "",
    isDuplicate: row.is_duplicate || false,
    duplicateOf: row.duplicate_of || "",
    hearAboutUs: row.hear_about_us || "",
    acquisitionStrategy: row.acquisition_strategy || "",
    buyerType: row.buyer_type || "",
    firefliesUrl: row.fireflies_url || "",
    firefliesTranscript: row.fireflies_transcript || "",
    firefliesSummary: row.fireflies_summary || "",
    firefliesNextSteps: row.fireflies_next_steps || "",
    linkedinUrl: row.linkedin_url || "",
    linkedinTitle: row.linkedin_title || "",
    linkedinSearchLog: row.linkedin_search_log || undefined,
    meetings: Array.isArray(row.meetings) ? row.meetings : [],
    submissions: Array.isArray(row.submissions) ? row.submissions : [],
    enrichment: row.enrichment || undefined,
    dealIntelligence: row.deal_intelligence || undefined,
    stage1Score: row.stage1_score != null ? Number(row.stage1_score) : null,
    stage2Score: row.stage2_score != null ? Number(row.stage2_score) : null,
    tier: row.tier != null ? Number(row.tier) : null,
    tierOverride: row.tier_override || false,
    enrichmentStatus: row.enrichment_status || "",
    createdAt: row.created_at || "",
    calendlyBookedAt: row.calendly_booked_at || "",
    calendlyEventName: row.calendly_event_name || "",
    calendlyEventType: row.calendly_event_type || "",
    calendlyEventDuration: row.calendly_event_duration != null ? Number(row.calendly_event_duration) : null,
    secondaryContacts: Array.isArray(row.secondary_contacts) ? row.secondary_contacts : [],
    googleDriveLink: row.google_drive_link || "",
    forecastedCloseDate: row.forecasted_close_date || "",
    nextMutualStep: row.next_mutual_step || "",
    nextMutualStepDate: row.next_mutual_step_date || "",
    competingBankers: row.competing_bankers || "",
    contractMonths: row.contract_months != null ? Number(row.contract_months) : null,
    closeConfidence: row.close_confidence != null ? Number(row.close_confidence) : null,
    dealNarrative: row.deal_narrative || "",
    firmAum: row.firm_aum || "",
    acqTimeline: row.acq_timeline || "",
    activeSearches: row.active_searches || "",
    budgetConfirmed: row.budget_confirmed || "",
    authorityConfirmed: row.authority_confirmed || "",
    ebitdaMin: row.ebitda_min || "",
    ebitdaMax: row.ebitda_max || "",
    dealType: row.deal_type || "",
    transactionType: row.transaction_type || "",
    competingAgainst: row.competing_against || "",
    decisionBlocker: row.decision_blocker || "",
    sampleSentDate: row.sample_sent_date || "",
    sampleOutcome: row.sample_outcome || "",
    proofNotes: row.proof_notes || "",
    stallReason: row.stall_reason || "",
    // v2 pipeline fields
    lostReasonV2: row.lost_reason_v2 || "",
    nurtureSequenceStatus: row.nurture_sequence_status ?? null,
    nurtureStartedAt: row.nurture_started_at ?? null,
    nurtureReEngageDate: row.nurture_re_engage_date ?? null,
    stageGateOverrides: Array.isArray(row.stage_gate_overrides) ? row.stage_gate_overrides : [],
    discoveryCallCompletedAt: row.discovery_call_completed_at ?? null,
  };
}

/** Convert partial Lead updates to partial DB row */
export function leadUpdatesToRow(updates: Partial<Lead>): Record<string, any> {
  const map: Record<string, string> = {
    brand: "brand", name: "name", email: "email", phone: "phone",
    company: "company", companyUrl: "company_url", role: "role",
    source: "source", dateSubmitted: "date_submitted", message: "message",
    dealsPlanned: "deals_planned", stage: "stage", serviceInterest: "service_interest",
    dealValue: "deal_value", assignedTo: "assigned_to", meetingDate: "meeting_date",
    meetingSetDate: "meeting_set_date", hoursToMeetingSet: "hours_to_meeting_set",
    daysInCurrentStage: "days_in_current_stage", stageEnteredDate: "stage_entered_date",
    closeReason: "close_reason", closedDate: "closed_date", notes: "notes",
    lastContactDate: "last_contact_date", nextFollowUp: "next_follow_up",
    priority: "priority", meetingOutcome: "meeting_outcome",
    forecastCategory: "forecast_category", icpFit: "icp_fit",
    preScreenCompleted: "pre_screen_completed",
    wonReason: "won_reason", lostReason: "lost_reason",
    subscriptionValue: "subscription_value", billingFrequency: "billing_frequency",
    contractStart: "contract_start", contractEnd: "contract_end",
    targetCriteria: "target_criteria", targetRevenue: "target_revenue",
    geography: "geography", currentSourcing: "current_sourcing",
    isDuplicate: "is_duplicate", duplicateOf: "duplicate_of",
    hearAboutUs: "hear_about_us", acquisitionStrategy: "acquisition_strategy",
    buyerType: "buyer_type", firefliesUrl: "fireflies_url",
    firefliesTranscript: "fireflies_transcript", firefliesSummary: "fireflies_summary",
    firefliesNextSteps: "fireflies_next_steps",
    meetings: "meetings", submissions: "submissions",
    enrichment: "enrichment", dealIntelligence: "deal_intelligence",
    linkedinUrl: "linkedin_url", linkedinTitle: "linkedin_title",
    stage1Score: "stage1_score", stage2Score: "stage2_score",
    tier: "tier", tierOverride: "tier_override", enrichmentStatus: "enrichment_status",
    createdAt: "created_at",
    calendlyBookedAt: "calendly_booked_at",
    calendlyEventName: "calendly_event_name",
    calendlyEventType: "calendly_event_type",
    calendlyEventDuration: "calendly_event_duration",
    secondaryContacts: "secondary_contacts",
    googleDriveLink: "google_drive_link",
    forecastedCloseDate: "forecasted_close_date",
    nextMutualStep: "next_mutual_step",
    nextMutualStepDate: "next_mutual_step_date",
    competingBankers: "competing_bankers",
    contractMonths: "contract_months",
    closeConfidence: "close_confidence",
    dealNarrative: "deal_narrative",
    firmAum: "firm_aum",
    acqTimeline: "acq_timeline",
    activeSearches: "active_searches",
    budgetConfirmed: "budget_confirmed",
    authorityConfirmed: "authority_confirmed",
    ebitdaMin: "ebitda_min",
    ebitdaMax: "ebitda_max",
    dealType: "deal_type",
    transactionType: "transaction_type",
    competingAgainst: "competing_against",
    decisionBlocker: "decision_blocker",
    sampleSentDate: "sample_sent_date",
    sampleOutcome: "sample_outcome",
    proofNotes: "proof_notes",
    stallReason: "stall_reason",
    // v2 pipeline fields
    lostReasonV2: "lost_reason_v2",
    nurtureSequenceStatus: "nurture_sequence_status",
    nurtureStartedAt: "nurture_started_at",
    nurtureReEngageDate: "nurture_re_engage_date",
    stageGateOverrides: "stage_gate_overrides",
    discoveryCallCompletedAt: "discovery_call_completed_at",
  };

  const row: Record<string, any> = {};
  for (const [key, value] of Object.entries(updates)) {
    const dbKey = map[key];
    if (dbKey) {
      row[dbKey] = value;
    }
  }
  return row;
}
