import { Lead } from "@/types/lead";

/** Convert a Lead object to a database row (camelCase → snake_case) */
export function leadToRow(lead: Lead): Record<string, any> {
  return {
    id: lead.id,
    brand: lead.brand,
    name: lead.name,
    email: lead.email,
    phone: lead.phone,
    company: lead.company,
    company_url: lead.companyUrl,
    role: lead.role,
    source: lead.source,
    date_submitted: lead.dateSubmitted,
    message: lead.message,
    deals_planned: lead.dealsPlanned,
    stage: lead.stage,
    service_interest: lead.serviceInterest,
    deal_value: lead.dealValue,
    assigned_to: lead.assignedTo,
    meeting_date: lead.meetingDate,
    meeting_set_date: lead.meetingSetDate,
    hours_to_meeting_set: lead.hoursToMeetingSet,
    days_in_current_stage: lead.daysInCurrentStage,
    stage_entered_date: lead.stageEnteredDate,
    close_reason: lead.closeReason,
    closed_date: lead.closedDate,
    notes: lead.notes,
    last_contact_date: lead.lastContactDate,
    next_follow_up: lead.nextFollowUp,
    priority: lead.priority,
    meeting_outcome: lead.meetingOutcome,
    forecast_category: lead.forecastCategory,
    icp_fit: lead.icpFit,
    pre_screen_completed: lead.preScreenCompleted ?? false,
    won_reason: lead.wonReason,
    lost_reason: lead.lostReason,
    subscription_value: lead.subscriptionValue,
    billing_frequency: lead.billingFrequency,
    contract_start: lead.contractStart,
    contract_end: lead.contractEnd,
    target_criteria: lead.targetCriteria,
    target_revenue: lead.targetRevenue,
    geography: lead.geography,
    current_sourcing: lead.currentSourcing,
    is_duplicate: lead.isDuplicate,
    duplicate_of: lead.duplicateOf,
    hear_about_us: lead.hearAboutUs,
    acquisition_strategy: lead.acquisitionStrategy,
    buyer_type: lead.buyerType,
    fireflies_url: lead.firefliesUrl,
    fireflies_transcript: lead.firefliesTranscript,
    fireflies_summary: lead.firefliesSummary,
    fireflies_next_steps: lead.firefliesNextSteps,
    linkedin_url: lead.linkedinUrl,
    linkedin_title: lead.linkedinTitle,
    meetings: lead.meetings || [],
    submissions: lead.submissions || [],
    enrichment: lead.enrichment || null,
    deal_intelligence: lead.dealIntelligence || null,
    stage1_score: lead.stage1Score,
    stage2_score: lead.stage2Score,
    tier: lead.tier,
    tier_override: lead.tierOverride,
    enrichment_status: lead.enrichmentStatus,
    created_at: lead.createdAt,
  };
}

/** Convert a database row to a Lead object (snake_case → camelCase) */
export function rowToLead(row: Record<string, any>): Lead {
  return {
    id: row.id,
    brand: row.brand,
    name: row.name,
    email: row.email,
    phone: row.phone,
    company: row.company,
    companyUrl: row.company_url || "",
    role: row.role,
    source: row.source,
    dateSubmitted: row.date_submitted || "",
    message: row.message || "",
    dealsPlanned: row.deals_planned || "",
    stage: row.stage,
    serviceInterest: row.service_interest || "TBD",
    dealValue: Number(row.deal_value) || 0,
    assignedTo: row.assigned_to || "",
    meetingDate: row.meeting_date || "",
    meetingSetDate: row.meeting_set_date || "",
    hoursToMeetingSet: row.hours_to_meeting_set != null ? Number(row.hours_to_meeting_set) : null,
    daysInCurrentStage: Number(row.days_in_current_stage) || 0,
    stageEnteredDate: row.stage_entered_date || "",
    closeReason: row.close_reason || "",
    closedDate: row.closed_date || "",
    notes: row.notes || "",
    lastContactDate: row.last_contact_date || "",
    nextFollowUp: row.next_follow_up || "",
    priority: row.priority || "Medium",
    meetingOutcome: row.meeting_outcome || "",
    forecastCategory: row.forecast_category || "",
    icpFit: row.icp_fit || "",
    preScreenCompleted: row.pre_screen_completed ?? false,
    wonReason: row.won_reason || "",
    lostReason: row.lost_reason || "",
    subscriptionValue: Number(row.subscription_value) || 0,
    billingFrequency: row.billing_frequency || "",
    contractStart: row.contract_start || "",
    contractEnd: row.contract_end || "",
    targetCriteria: row.target_criteria || "",
    targetRevenue: row.target_revenue || "",
    geography: row.geography || "",
    currentSourcing: row.current_sourcing || "",
    isDuplicate: row.is_duplicate || false,
    duplicateOf: row.duplicate_of || "",
    hearAboutUs: row.hear_about_us || "",
    acquisitionStrategy: row.acquisition_strategy || "",
    buyerType: row.buyer_type || "",
    firefliesUrl: row.fireflies_url || "",
    firefliesTranscript: row.fireflies_transcript || "",
    firefliesSummary: row.fireflies_summary || "",
    firefliesNextSteps: row.fireflies_next_steps || "",
    linkedinUrl: row.linkedin_url || "",
    linkedinTitle: row.linkedin_title || "",
    meetings: Array.isArray(row.meetings) ? row.meetings : [],
    submissions: Array.isArray(row.submissions) ? row.submissions : [],
    enrichment: row.enrichment || undefined,
    dealIntelligence: row.deal_intelligence || undefined,
    stage1Score: row.stage1_score != null ? Number(row.stage1_score) : null,
    stage2Score: row.stage2_score != null ? Number(row.stage2_score) : null,
    tier: row.tier != null ? Number(row.tier) : null,
    tierOverride: row.tier_override || false,
    enrichmentStatus: row.enrichment_status || "",
  };
}

/** Convert partial Lead updates to partial DB row */
export function leadUpdatesToRow(updates: Partial<Lead>): Record<string, any> {
  const map: Record<string, string> = {
    brand: "brand", name: "name", email: "email", phone: "phone",
    company: "company", companyUrl: "company_url", role: "role",
    source: "source", dateSubmitted: "date_submitted", message: "message",
    dealsPlanned: "deals_planned", stage: "stage", serviceInterest: "service_interest",
    dealValue: "deal_value", assignedTo: "assigned_to", meetingDate: "meeting_date",
    meetingSetDate: "meeting_set_date", hoursToMeetingSet: "hours_to_meeting_set",
    daysInCurrentStage: "days_in_current_stage", stageEnteredDate: "stage_entered_date",
    closeReason: "close_reason", closedDate: "closed_date", notes: "notes",
    lastContactDate: "last_contact_date", nextFollowUp: "next_follow_up",
    priority: "priority", meetingOutcome: "meeting_outcome",
    forecastCategory: "forecast_category", icpFit: "icp_fit",
    preScreenCompleted: "pre_screen_completed",
    wonReason: "won_reason", lostReason: "lost_reason",
    subscriptionValue: "subscription_value", billingFrequency: "billing_frequency",
    contractStart: "contract_start", contractEnd: "contract_end",
    targetCriteria: "target_criteria", targetRevenue: "target_revenue",
    geography: "geography", currentSourcing: "current_sourcing",
    isDuplicate: "is_duplicate", duplicateOf: "duplicate_of",
    hearAboutUs: "hear_about_us", acquisitionStrategy: "acquisition_strategy",
    buyerType: "buyer_type", firefliesUrl: "fireflies_url",
    firefliesTranscript: "fireflies_transcript", firefliesSummary: "fireflies_summary",
    firefliesNextSteps: "fireflies_next_steps",
    meetings: "meetings", submissions: "submissions",
    enrichment: "enrichment", dealIntelligence: "deal_intelligence",
    linkedinUrl: "linkedin_url", linkedinTitle: "linkedin_title",
    stage1Score: "stage1_score", stage2Score: "stage2_score",
    tier: "tier", tierOverride: "tier_override", enrichmentStatus: "enrichment_status",
  };

  const row: Record<string, any> = {};
  for (const [key, value] of Object.entries(updates)) {
    const dbKey = map[key];
    if (dbKey) {
      row[dbKey] = value;
    }
  }
  return row;
}
