// nurture-engine — daily cron driving the 90-day post-loss nurture sequence (S8).
//
// Triggered by pg_cron once per day. For every Closed Lost lead with
// nurture_sequence_status = 'active', emits drafts/tasks at the right milestones:
//   d0  → AI-personalized "insight email"  (queued in lead_drafts, manual approve)
//   d30 → AI-personalized "market update"  (queued draft)
//   d45 → "Manual call task"               (lead_tasks — Malik writes the touch himself)
//   d90 → AI-personalized "re-open ask"    (queued draft + task)
// On d97 the cron flips status to 'completed' so it stops firing. If a reply
// comes in (via lead_email_metrics last_received_date > nurture_started_at),
// status becomes 're_engaged' and the deal is moved back to "In Contact".
//
// Idempotent: each milestone uses a deterministic playbook key + lead_id so
// re-runs don't duplicate. Drafts are de-duped on (lead_id, draft_type).
//
// Personalization: AI copy is generated by `generate-nurture-email` per
// milestone using lost_reason_v2 + sector + EBITDA + acquisition timeline +
// buyer type. Falls back to a sensible static template on AI failure so the
// cron never silently produces empty drafts.
//
// Step log: every emitted draft / completed step is appended to
// leads.nurture_step_log (jsonb array of {step, sent_at, draft_id, replied}).
// The Sequences UI reads this directly for the funnel + activity feed.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.50.0";
import { logCronRun } from "../_shared/cron-log.ts";

const JOB_NAME = "nurture-engine";
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

interface Lead {
  id: string;
  name: string;
  company: string;
  email: string;
  brand: string;
  stage: string;
  nurture_started_at: string;
  nurture_re_engage_date: string | null;
  nurture_sequence_status: string;
  nurture_step_log: Array<{ step: string; sent_at: string; draft_id?: string; email_id?: string; replied?: boolean }>;
  lost_reason_v2: string;
  deal_type: string;
  acquisition_strategy: string;
  ebitda_min: string;
  ebitda_max: string;
  acq_timeline: string;
  buyer_type: string;
  geography: string;
  fireflies_url: string;
}

const DAY = 86400 * 1000;

function dayOffset(startedAt: string): number {
  const start = new Date(startedAt).getTime();
  return Math.floor((Date.now() - start) / DAY);
}

function firstName(name: string): string {
  return (name || "").split(" ")[0] || "there";
}

async function appendStepLog(
  supabase: any,
  lead: Lead,
  step: string,
  draftId?: string,
) {
  const next = Array.isArray(lead.nurture_step_log) ? [...lead.nurture_step_log] : [];
  if (next.some((e) => e.step === step)) return;
  next.push({ step, sent_at: new Date().toISOString(), draft_id: draftId, replied: false });
  await supabase.from("leads").update({ nurture_step_log: next } as any).eq("id", lead.id);
  lead.nurture_step_log = next;
}

async function ensureTask(
  supabase: any,
  leadId: string,
  playbook: string,
  title: string,
  description: string,
  taskType: "email" | "call" | "internal",
  dueDateOffsetDays: number,
): Promise<boolean> {
  const { data: existing } = await supabase
    .from("lead_tasks")
    .select("id")
    .eq("lead_id", leadId)
    .eq("playbook", playbook)
    .limit(1);
  if (existing && existing.length > 0) return false;

  const dueDate = new Date(Date.now() + dueDateOffsetDays * DAY).toISOString().slice(0, 10);
  await supabase.from("lead_tasks").insert({
    lead_id: leadId,
    playbook,
    sequence_order: 1,
    task_type: taskType,
    title,
    description,
    due_date: dueDate,
  });
  return true;
}

async function generateAICopy(lead: Lead, day: 0 | 30 | 90): Promise<{ subject: string; body: string }> {
  try {
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/generate-nurture-email`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      },
      body: JSON.stringify({
        day,
        brand: lead.brand,
        firstName: lead.name,
        company: lead.company,
        lostReason: lead.lost_reason_v2,
        sector: lead.deal_type || lead.acquisition_strategy,
        ebitdaMin: lead.ebitda_min,
        ebitdaMax: lead.ebitda_max,
        acqTimeline: lead.acq_timeline,
        buyerType: lead.buyer_type,
        geography: lead.geography,
      }),
    });
    if (resp.ok) {
      const j = await resp.json();
      if (j.ok && j.subject && j.body) return { subject: j.subject, body: j.body };
    }
  } catch (e) {
    console.error(`AI gen failed for ${lead.id} day ${day}`, e);
  }
  // Fallback static copy — keeps the cron flowing if AI is down.
  const fn = firstName(lead.name);
  if (day === 0) return {
    subject: "Thought of you",
    body: `Hi ${fn},\n\nThinking about ${lead.company || "your search"}. One observation from a recent ${lead.brand} deal that reminded me of your situation. Worth a 10 minute call to compare notes?\n\nMalik`,
  };
  if (day === 30) return {
    subject: "Quick market read",
    body: `Hi ${fn},\n\nMarket update on the segment we discussed. Two trends worth flagging. Happy to share the underlying data if useful.\n\nMalik`,
  };
  return {
    subject: "Worth a reset?",
    body: `Hi ${fn},\n\nIt has been about 90 days. We have helped a few similar buyers source targets recently. Open to a quick reset?\n\nMalik`,
  };
}

async function ensureNurtureDraft(
  supabase: any,
  lead: Lead,
  day: 0 | 30 | 90,
  contextLabel: string,
): Promise<string | null> {
  const draftType = `nurture-d${day}`;
  const { data: existing } = await supabase
    .from("lead_drafts")
    .select("id")
    .eq("lead_id", lead.id)
    .eq("draft_type", draftType)
    .limit(1);
  if (existing && existing.length > 0) return null;

  const { subject, body } = await generateAICopy(lead, day);
  const content = `Subject: ${subject}\n\n${body}`;

  const { data: inserted } = await supabase
    .from("lead_drafts")
    .insert({
      lead_id: lead.id,
      draft_type: draftType,
      action_key: `N${day}`,
      context_label: contextLabel,
      content,
      status: "pending_review",
    })
    .select("id")
    .single();

  await supabase.from("lead_activity_log").insert({
    lead_id: lead.id,
    event_type: "nurture_draft_emitted",
    description: `Nurture step N${day} draft generated: ${subject}`,
    new_value: `N${day}`,
    metadata: { step: `N${day}`, draft_id: inserted?.id, subject },
  } as any);

  await appendStepLog(supabase, lead, `N${day}`, inserted?.id);
  return inserted?.id ?? null;
}

async function handleScopeMismatchExit(supabase: any, lead: Lead): Promise<boolean> {
  // Single referral email, no further touches.
  const draftType = "nurture-referral";
  const { data: existing } = await supabase
    .from("lead_drafts")
    .select("id")
    .eq("lead_id", lead.id)
    .eq("draft_type", draftType)
    .limit(1);
  if (!existing || existing.length === 0) {
    const fn = firstName(lead.name);
    const content = `Subject: Better fit elsewhere\n\nHi ${fn},\n\nFollowing our conversation, your mandate sits outside what we cover. Two firms I would point you to: [insert names]. Both are operators I trust in this segment. Happy to make an intro.\n\nMalik`;
    const { data: inserted } = await supabase
      .from("lead_drafts")
      .insert({
        lead_id: lead.id,
        draft_type: draftType,
        action_key: "referral",
        context_label: "Scope mismatch referral",
        content,
        status: "pending_review",
      })
      .select("id")
      .single();
    await appendStepLog(supabase, lead, "REFERRAL", inserted?.id);
  }
  await supabase.from("leads").update({
    nurture_sequence_status: "exited_referral",
    nurture_exit_reason: "Scope Mismatch",
  } as any).eq("id", lead.id);
  await supabase.from("lead_activity_log").insert({
    lead_id: lead.id,
    event_type: "nurture_exited",
    description: "Exited 90-day nurture: Scope Mismatch — referral email queued",
    old_value: "active",
    new_value: "exited_referral",
  } as any);
  return true;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  let drafts = 0, tasks = 0, completed = 0, reEngaged = 0, exited = 0, processed = 0;
  try {
    const { data: leads, error } = await supabase
      .from("leads")
      .select("id,name,company,email,brand,stage,nurture_started_at,nurture_re_engage_date,nurture_sequence_status,nurture_step_log,lost_reason_v2,deal_type,acquisition_strategy,ebitda_min,ebitda_max,acq_timeline,buyer_type,geography,fireflies_url")
      .eq("nurture_sequence_status", "active")
      .is("archived_at", null);
    if (error) throw error;
    if (!leads || leads.length === 0) {
      await logCronRun(JOB_NAME, "noop", 0, { drafts, tasks, completed, reEngaged, exited });
      return new Response(JSON.stringify({ ok: true, processed: 0 }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    processed = leads.length;

    for (const lead of leads as Lead[]) {
      if (!lead.nurture_started_at) continue;

      // ── Scope Mismatch exit branch ─────────────────────────
      // Catches leads enrolled before the LeadContext guard shipped.
      if (lead.lost_reason_v2 === "Scope Mismatch") {
        await handleScopeMismatchExit(supabase, lead);
        exited++;
        continue;
      }

      const day = dayOffset(lead.nurture_started_at);

      // ── Re-engagement detection ────────────────────────────
      const { data: metrics } = await supabase
        .from("lead_email_metrics")
        .select("last_received_date,last_replied_date")
        .eq("lead_id", lead.id)
        .maybeSingle();
      const lastInbound = metrics?.last_received_date ?? metrics?.last_replied_date;
      if (lastInbound && new Date(lastInbound) > new Date(lead.nurture_started_at)) {
        await supabase.from("leads").update({
          nurture_sequence_status: "re_engaged",
          stage: "In Contact",
          stage_entered_date: new Date().toISOString().slice(0, 10),
        } as any).eq("id", lead.id);
        await supabase.from("lead_activity_log").insert({
          lead_id: lead.id,
          event_type: "nurture_re_engaged",
          description: "Prospect responded during 90-day nurture: moved back to In Contact",
          old_value: "Closed Lost",
          new_value: "In Contact",
        } as any);
        reEngaged++;
        continue;
      }

      // ── Milestone drafts (idempotent via draft_type) ───────
      if (day >= 0 && await ensureNurtureDraft(supabase, lead, 0, "Day 0 — insight email")) drafts++;
      if (day >= 30 && await ensureNurtureDraft(supabase, lead, 30, "Day 30 — market update")) drafts++;

      // ── Day 45 stays manual: surface Fireflies transcript inline ──
      if (day >= 45) {
        const ffLine = lead.fireflies_url ? `\nFireflies transcript: ${lead.fireflies_url}` : "";
        if (await ensureTask(
          supabase, lead.id, "nurture-d45",
          "Day 45 — manual call check-in",
          `Pick up the phone. Reference one specific moment from the original conversation. Goal: re-open, not pitch.${ffLine}`,
          "call", 0,
        )) {
          tasks++;
          await appendStepLog(supabase, lead, "N45");
        }
      }

      // ── Day 90 AI re-open ask + close-out task ────────────
      if (day >= 90) {
        if (await ensureNurtureDraft(supabase, lead, 90, "Day 90 — re-open ask")) drafts++;
        if (await ensureTask(
          supabase, lead.id, "nurture-d90-task",
          "Day 90 — send re-open ask",
          "Review and send the AI-drafted re-open ask. If no reply within 7 days, sequence auto-completes.",
          "email", 0,
        )) tasks++;

        // Auto-complete after 7-day grace window.
        if (day >= 97) {
          await supabase.from("leads").update({
            nurture_sequence_status: "completed",
          } as any).eq("id", lead.id);
          await supabase.from("lead_activity_log").insert({
            lead_id: lead.id,
            event_type: "nurture_completed",
            description: "90-day nurture sequence completed without re-engagement",
          } as any);
          completed++;
        }
      }
    }

    await logCronRun(JOB_NAME, "success", processed, { drafts, tasks, completed, reEngaged, exited });
    return new Response(
      JSON.stringify({ ok: true, processed, drafts, tasks, completed, reEngaged, exited }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (e) {
    console.error("nurture-engine error", e);
    await logCronRun(JOB_NAME, "error", processed, { drafts, tasks }, String(e));
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
