ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS stage1_score integer,
  ADD COLUMN IF NOT EXISTS stage2_score integer,
  ADD COLUMN IF NOT EXISTS tier integer,
  ADD COLUMN IF NOT EXISTS tier_override boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS enrichment_status text DEFAULT '',
  ADD COLUMN IF NOT EXISTS known_firm_match text,
  ADD COLUMN IF NOT EXISTS known_firm_domain_type text,
  ADD COLUMN IF NOT EXISTS pe_backed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS pe_sponsor_name text,
  ADD COLUMN IF NOT EXISTS website_url text,
  ADD COLUMN IF NOT EXISTS website_score integer,
  ADD COLUMN IF NOT EXISTS pe_backed_stage2 boolean,
  ADD COLUMN IF NOT EXISTS portfolio_count integer,
  ADD COLUMN IF NOT EXISTS last_acquisition_year integer,
  ADD COLUMN IF NOT EXISTS linkedin_url text,
  ADD COLUMN IF NOT EXISTS linkedin_title text,
  ADD COLUMN IF NOT EXISTS linkedin_ma_experience boolean,
  ADD COLUMN IF NOT EXISTS linkedin_score integer,
  ADD COLUMN IF NOT EXISTS seniority_score integer;